database:
  driver-name: "mysql"
  club-source-name: "${MYSQLUSER}:${MYSQLPASSWORD}@tcp(${MYSQLHOST}:${MYSQLPORT})/${MYSQLDATABASE}?charset=utf8mb4&parseTime=True&loc=Local"
  spin-source-name: "${MYSQLUSER}:${MYSQLPASSWORD}@tcp(${MYSQLHOST}:${MYSQLPORT})/${MYSQLDATABASE}?charset=utf8mb4&parseTime=True&loc=Local"
  use-spin-log: true
